
package com.obiectumclaro.factronica.core.web.service.sri.client.authorization;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AutorizacionComprobantes", targetNamespace = "http://ec.gob.sri.ws.autorizacion")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AutorizacionComprobantes {


    /**
     * 
     * @param claveAccesoComprobante
     * @return
     *     returns RespuestaComprobante
     */
    @WebMethod
    @WebResult(name = "RespuestaAutorizacionComprobante", targetNamespace = "")
    @RequestWrapper(localName = "autorizacionComprobante", targetNamespace = "http://ec.gob.sri.ws.autorizacion", className = "com.obiectumclaro.factronica.core.web.service.sri.client.authorization.AutorizacionComprobante")
    @ResponseWrapper(localName = "autorizacionComprobanteResponse", targetNamespace = "http://ec.gob.sri.ws.autorizacion", className = "com.obiectumclaro.factronica.core.web.service.sri.client.authorization.AutorizacionComprobanteResponse")
    public RespuestaComprobante autorizacionComprobante(
        @WebParam(name = "claveAccesoComprobante", targetNamespace = "")
        String claveAccesoComprobante);

    /**
     * 
     * @param claveAccesoLote
     * @return
     *     returns RespuestaLote
     */
    @WebMethod
    @WebResult(name = "RespuestaAutorizacionLote", targetNamespace = "")
    @RequestWrapper(localName = "autorizacionComprobanteLote", targetNamespace = "http://ec.gob.sri.ws.autorizacion", className = "com.obiectumclaro.factronica.core.web.service.sri.client.authorization.AutorizacionComprobanteLote")
    @ResponseWrapper(localName = "autorizacionComprobanteLoteResponse", targetNamespace = "http://ec.gob.sri.ws.autorizacion", className = "com.obiectumclaro.factronica.core.web.service.sri.client.authorization.AutorizacionComprobanteLoteResponse")
    public RespuestaLote autorizacionComprobanteLote(
        @WebParam(name = "claveAccesoLote", targetNamespace = "")
        String claveAccesoLote);

}
