
package com.obiectumclaro.factronica.core.web.service.sri.client.authorization;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AutorizacionComprobantesService", targetNamespace = "http://ec.gob.sri.ws.autorizacion", wsdlLocation = "https://celcer.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantes?wsdl")
public class AutorizacionComprobantesService
    extends Service
{

    private final static URL AUTORIZACIONCOMPROBANTESSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(AutorizacionComprobantesService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = AutorizacionComprobantesService.class.getResource(".");
            url = new URL(baseUrl, "https://celcer.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantes?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://celcer.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantes?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        AUTORIZACIONCOMPROBANTESSERVICE_WSDL_LOCATION = url;
    }

    public AutorizacionComprobantesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutorizacionComprobantesService() {
        super(AUTORIZACIONCOMPROBANTESSERVICE_WSDL_LOCATION, new QName("http://ec.gob.sri.ws.autorizacion", "AutorizacionComprobantesService"));
    }

    /**
     * 
     * @return
     *     returns AutorizacionComprobantes
     */
    @WebEndpoint(name = "AutorizacionComprobantesPort")
    public AutorizacionComprobantes getAutorizacionComprobantesPort() {
        return super.getPort(new QName("http://ec.gob.sri.ws.autorizacion", "AutorizacionComprobantesPort"), AutorizacionComprobantes.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutorizacionComprobantes
     */
    @WebEndpoint(name = "AutorizacionComprobantesPort")
    public AutorizacionComprobantes getAutorizacionComprobantesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ec.gob.sri.ws.autorizacion", "AutorizacionComprobantesPort"), AutorizacionComprobantes.class, features);
    }

}
