//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.28 at 07:25:04 PM ECT 
//


package com.obiectumclaro.factronica.core.model.xsd.invoice;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.obiectumclaro.factronica.model.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.obiectumclaro.factronica.model.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Factura }
     * 
     */
    public SignedInvoice createFactura() {
        return new SignedInvoice();
    }

    /**
     * Create an instance of {@link Factura.InfoAdicional }
     * 
     */
    public SignedInvoice.InfoAdicional createFacturaInfoAdicional() {
        return new SignedInvoice.InfoAdicional();
    }

    /**
     * Create an instance of {@link Factura.Detalles }
     * 
     */
    public SignedInvoice.Detalles createFacturaDetalles() {
        return new SignedInvoice.Detalles();
    }

    /**
     * Create an instance of {@link Factura.Detalles.Detalle }
     * 
     */
    public SignedInvoice.Detalles.Detalle createFacturaDetallesDetalle() {
        return new SignedInvoice.Detalles.Detalle();
    }

    /**
     * Create an instance of {@link Factura.Detalles.Detalle.DetallesAdicionales }
     * 
     */
    public SignedInvoice.Detalles.Detalle.DetallesAdicionales createFacturaDetallesDetalleDetallesAdicionales() {
        return new SignedInvoice.Detalles.Detalle.DetallesAdicionales();
    }

    /**
     * Create an instance of {@link Factura.InfoFactura }
     * 
     */
    public SignedInvoice.InfoFactura createFacturaInfoFactura() {
        return new SignedInvoice.InfoFactura();
    }

    /**
     * Create an instance of {@link Factura.InfoFactura.TotalConImpuestos }
     * 
     */
    public SignedInvoice.InfoFactura.TotalConImpuestos createFacturaInfoFacturaTotalConImpuestos() {
        return new SignedInvoice.InfoFactura.TotalConImpuestos();
    }

    /**
     * Create an instance of {@link InfoTributaria }
     * 
     */
    public TaxInformation createInfoTributaria() {
        return new TaxInformation(null, null);
    }

    /**
     * Create an instance of {@link Impuesto }
     * 
     */
    public Tax createImpuesto() {
        return new Tax();
    }

    /**
     * Create an instance of {@link Factura.InfoAdicional.CampoAdicional }
     * 
     */
    public SignedInvoice.InfoAdicional.CampoAdicional createFacturaInfoAdicionalCampoAdicional() {
        return new SignedInvoice.InfoAdicional.CampoAdicional();
    }

    /**
     * Create an instance of {@link Factura.Detalles.Detalle.Impuestos }
     * 
     */
    public SignedInvoice.Detalles.Detalle.Impuestos createFacturaDetallesDetalleImpuestos() {
        return new SignedInvoice.Detalles.Detalle.Impuestos();
    }

    /**
     * Create an instance of {@link Factura.Detalles.Detalle.DetallesAdicionales.DetAdicional }
     * 
     */
    public SignedInvoice.Detalles.Detalle.DetallesAdicionales.DetAdicional createFacturaDetallesDetalleDetallesAdicionalesDetAdicional() {
        return new SignedInvoice.Detalles.Detalle.DetallesAdicionales.DetAdicional();
    }

    /**
     * Create an instance of {@link Factura.InfoFactura.TotalConImpuestos.TotalImpuesto }
     * 
     */
    public SignedInvoice.InfoFactura.TotalConImpuestos.TotalImpuesto createFacturaInfoFacturaTotalConImpuestosTotalImpuesto() {
        return new SignedInvoice.InfoFactura.TotalConImpuestos.TotalImpuesto();
    }

}
