//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.25 at 11:41:03 AM ECT 
//


package com.obiectumclaro.factronica.core.model.xsd.nota.credito;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TotalConImpuestos.TotalImpuesto }
     * 
     */
    public TotalConImpuestos.TotalImpuesto createTotalConImpuestosTotalImpuesto() {
        return new TotalConImpuestos.TotalImpuesto();
    }

    /**
     * Create an instance of {@link Impuesto }
     * 
     */
    public Impuesto createImpuesto() {
        return new Impuesto();
    }

    /**
     * Create an instance of {@link generated.Detalle }
     * 
     */
    public Detalle createDetalle() {
        return new  Detalle();
    }

    /**
     * Create an instance of {@link NotaCredito.Detalles.Detalle.DetallesAdicionales }
     * 
     */
    public NotaCredito.Detalles.Detalle.DetallesAdicionales createNotaCreditoDetallesDetalleDetallesAdicionales() {
        return new NotaCredito.Detalles.Detalle.DetallesAdicionales();
    }

    /**
     * Create an instance of {@link NotaCredito }
     * 
     */
    public NotaCredito createNotaCredito() {
        return new NotaCredito();
    }

    /**
     * Create an instance of {@link TotalConImpuestos }
     * 
     */
    public TotalConImpuestos createTotalConImpuestos() {
        return new TotalConImpuestos();
    }

    /**
     * Create an instance of {@link NotaCredito.InfoAdicional.CampoAdicional }
     * 
     */
    public NotaCredito.InfoAdicional.CampoAdicional createNotaCreditoInfoAdicionalCampoAdicional() {
        return new NotaCredito.InfoAdicional.CampoAdicional();
    }

    /**
     * Create an instance of {@link NotaCredito.Detalles.Detalle.Impuestos }
     * 
     */
    public NotaCredito.Detalles.Detalle.Impuestos createNotaCreditoDetallesDetalleImpuestos() {
        return new NotaCredito.Detalles.Detalle.Impuestos();
    }

    /**
     * Create an instance of {@link NotaCredito.Detalles }
     * 
     */
    public NotaCredito.Detalles createNotaCreditoDetalles() {
        return new NotaCredito.Detalles();
    }

    /**
     * Create an instance of {@link NotaCredito.Detalles.Detalle }
     * 
     */
    public NotaCredito.Detalles.Detalle createNotaCreditoDetallesDetalle() {
        return new NotaCredito.Detalles.Detalle();
    }

    /**
     * Create an instance of {@link NotaCredito.InfoAdicional }
     * 
     */
    public NotaCredito.InfoAdicional createNotaCreditoInfoAdicional() {
        return new NotaCredito.InfoAdicional();
    }

    /**
     * Create an instance of {@link InfoTributaria }
     * 
     */
    public InfoTributaria createInfoTributaria() {
        return new InfoTributaria();
    }

    /**
     * Create an instance of {@link NotaCredito.InfoNotaCredito }
     * 
     */
    public NotaCredito.InfoNotaCredito createNotaCreditoInfoNotaCredito() {
        return new NotaCredito.InfoNotaCredito();
    }

    /**
     * Create an instance of {@link NotaCredito.Detalles.Detalle.DetallesAdicionales.DetAdicional }
     * 
     */
    public NotaCredito.Detalles.Detalle.DetallesAdicionales.DetAdicional createNotaCreditoDetallesDetalleDetallesAdicionalesDetAdicional() {
        return new NotaCredito.Detalles.Detalle.DetallesAdicionales.DetAdicional();
    }

}
